# Generated by Django 2.0 on 2018-03-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180323_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='goal',
            new_name='reading_goal',
        ),
    ]
