# Generated by Django 2.0 on 2018-03-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20180319_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
