# Generated by Django 2.0 on 2018-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20180319_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css_class',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
