# Generated by Django 2.0 on 2018-03-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_page_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
